### ISSUE TITLE
Goodland Electricity

### ISSUE THREAD

**Issue by pri1311** [Nivedita967/Data-Structure-and-Algorithms#808] opened 2021-03-17 14:14 UTC
### Problem Link 
https://www.hackerrank.com/challenges/pylons/problem

### Coding platform
Hackerrank

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [x] Python

**Comment by pri1311** [comment] 2021-03-17 14:14
Please assign this issue to me under crosswoc for c++

**Comment by Nivedita967** [comment] 2021-03-19 15:31
Complete all the previous assigned first, then I will assign to these further.

**Comment by Amit366** [comment] 2021-03-26 15:01
@Nivedita967 my PR isn't reviewed and the issue is closed

**Closed** 2021-03-27 18:44 UTC
Labels: crossWoc, difficulty: medium
